### ISSUE TITLE
USER STORY: Create new product

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#11]
As a **Superuser** I can **add a new product to the database** so that **I can expand my assortment**

#2 Create and View Products

### Acceptance Criteria
As a Superuser I should be able to create new products through the admin panel or the front-end.

### Tasks
- [x] Create view to add a product
- [x] Create a template to add a new product
- [x] Add a "Create Product" button only for superusers on the front-end
- [x] Wire up views and URLS for "Create Product" button.
- [x] Ensure new Products are added to the database for other users to see.
