### ISSUE TITLE
USER STORY: Edit Products

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#11]
As a **Superuser** I can **Edit products** so that **I can keep all information updated**

#2  Create and View products

### Acceptance Criteria
Given that I am a Superuser I can edit a product either in the admin panel or the front-end

### Tasks
- [ ] Create a "Edit Product" button only visible for the superuser
- [ ] Create a view to edit product
- [ ] Wire up views and URLS for "Edit Product" button.
- [ ] Ensure new Product details are added to the database for other users to see.
