### ISSUE TITLE
USER STORY: Delete products

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#12]
As a **superuser** I can **delete products from the database** so that **remove obsolete products**

#2  Create and View Products

### Acceptance Criteria
Given that I am a Superuser I can delete products either from the admin panel or the front-end.

### Tasks
- [ ] Create a "Delete Product" button only visible for superusers
- [ ] Create a delete view
- [ ] Wire up views and URLS for "Delete Product" button.
- [ ] Ensure Products are Deleted from the database.
