### ISSUE TITLE
USER STORY: Edit Products

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#12]
As a **Superuser** I can **Edit products** so that **I can keep all information updated**

#2  Create and View products

### Acceptance Criteria
As  a Superuser I can edit a product either in the admin panel or the front-end

### Tasks
- [x] Create a "Edit Product" button only visible for the superuser
- [x] Create a template to edit a product
- [x] Create a view to edit product
- [x] Wire up views and URLS for "Edit Product" button.
- [x] Ensure new Product details are added to the database for other users to see.
