### ISSUE TITLE
USER STORY: Delete products 

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#13]
As a **superuser** I can **delete products from the database** so that **remove obsolete products**

#2  Create and View Products

### Acceptance Criteria
As a Superuser I can delete products either from the admin panel or the front-end.

### Tasks
- [x] Create a "Delete Product" button only visible for superusers
- [x] Create a delete view
- [x] Wire up views and URLS for "Delete Product" button.
- [x] Ensure Products are Deleted from the database.
