### ISSUE TITLE
USER STORY: Create Account

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#14]
As a **Site User** I can **create an account** so that **sign in and make use of the site full functionality**

#3  Sign/in and out

### Acceptance Criteria
- Given that I am a site user, who has no account, I should be able to create an account.
- Given that I am an unregistered user, When I am on the homepage, I can see a button to sign up and will be redirected to the registration page.
- Given that I am an unregistered user, and I am on the registration page, when I enter my username, email address and password I can create my account.

### Tasks
- [ ] Add button to register 
- [ ] Link button to views and URL that creates a user account.
- [ ] Set up email verification
