### ISSUE TITLE
USER STORY: Search for a product

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#14]
As a **Site User** I can **search for a product by a keyword** so that **I can find products relative to the keyword**

#1   Landing Page

### Acceptance Crtieria
As a Siteuser I should be able to easily find products by typing in a keyword in a search bar and see relevant products relative to my keyword.

### Tasks
- [x] Integrate a search bar to the navbar
- [x] create a view for the search 
- [x] Wire up view and URLs
