### ISSUE TITLE
USER STORY: View product

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#19]
As a **Site User** I can **See a list of products with the ability to click on each item for more information** so that **I can make informed purchases.**

#2 Create and View Products

### Acceptance Criteria
Given that I am a site user I can clearly see a list of products available for sale.
Given that I am a site user when I click on any of the products for sale I am brought to a page that displays more information about the product

### Tasks
- [ ] By clicking on a product, redirect the user to the PDP
- [ ] Create a PDP
- [ ] Create a view for PDP
- [ ] Wire view and URL up
