### ISSUE TITLE
USER STORY: View Products List by Segmentation

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#20]
As a **Site User** I can **select a certain segment** so that ** I can only view relevant products**

#2  Create and View Products

### Acceptance Criteria
- Given that I am a Site User I can clearly see select a certain activity of the product assortment and see a list of relevant products.
- Given that I am a Site User I can clearly see select a certain brand and see a list of relevant products

### Tasks
- [ ] Create a segment for activity
- [ ] Create a segment for brand
- [ ] Wire up the links in the navbar
