### ISSUE TITLE
USER STORY: View product

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#20]
As a **Site User** I can **See a list of products with the ability to click on each item for more information** so that **I can make informed purchases.**

#4  Create and View Products

### Acceptance Criteria

- As a site user, I should be able to view a comprehensive list of available products.
- As a site user, when I click on any product, I should be redirected to a product detail page (PDP) that displays relevant information about the product.

### Tasks
- [x] By clicking on a product, redirect the user to the PDP
- [x] Create a PDP
- [x] Create a view for PDP
- [x] Wire view and URL up
