### ISSUE TITLE
USER STORY: View Products List by Segmentation

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#21]
As a **Site User** I can **select a certain segment** so that **I can only view relevant products**

#2  Create and View Products

### Acceptance Criteria

- As a site user, I should be able to select a specific product segment, such as activity type, to view a list of relevant products.
- As a site user, I should be able to select a specific brand to view a list of relevant products.

### Tasks

- [x] Create a segment for activity
- [x] Create a segment for brand
- [x] Wire up the links in the navbar
