### ISSUE TITLE
USER STORY: Add to Cart

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#23]
As a **Site User** I can **add products to my cart** so that **can review my selected products and make a purchase**

#4  Shopping Cart and Checkout

### Acceptance Criteria
As a Site User, when I navigate to a product I want to purchase then I have the option to add it to a Cart.

### Tasks
- [x] Create an "Add to Cart" button on the PDP
- [x] Create a view
- [x] Wire up views and URLS for "Add to Cart" button.
- [x] Ensure items added to the cart are accessible all over the site.
