### ISSUE TITLE
USER STORY:

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#23]
As a **Site User** I can **view my shopping cart** so that **I have an overview of the items I want to purchase**

#4 Shopping Cart and Checkout

### Acceptance Criteria
- Given that I am a Site User, I can navigate to the Shopping cart page via the navbar
- Given that I am a Site User I can navigate to the Shopping cart page and see a total cost of the products contained within.

### Tasks
- [ ] Create an shopping Cart page
- [ ] Create a view
- [ ] Wire up views and URLS for Shopping cart page.
- [ ] Ensure Cart is visible and accessible all over the site.
