### ISSUE TITLE
USER STORY: View Cart

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#24]
As a **Site User** I can **view my shopping cart** so that **I have an overview of the items I want to purchase**

#4 Shopping Cart and Checkout

### Acceptance Criteria
-As a Site User, I can navigate to the Shopping cart page via the navbar
- As  a Site User I can navigate to the Shopping cart page and see a total cost of the products contained within.

### Tasks
- [x] Create an shopping Cart page
- [x] Create a view
- [x] Wire up views and URLS for Shopping cart page.
- [x] Ensure Cart is visible and accessible all over the site.

**Comment by kerstin-w** [comment]
Error Message on Shopping Bag page needs to be tested.
`if (quantity >= 1 && quantity <= 99) {
            form.submit();
        } else {
            messages.error(request, 'Please enter a quantity between 1 and 99');
            return false;
        }`
