### ISSUE TITLE
USER STORY: Edit Quantity from items in Cart

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#24]
As a **Site User** I can **adjust the quantity of a product in my cart** so that **purchase the quantity I desire**

#4 Shopping Cart and Checkout

### Acceptance Criteria
Given that I am a Site User, when I navigate to my Cart I can increase or decrease the quantity.

### Tasks
- [ ] Create + and - buttons 
- [ ] Add an update button
- [ ] Wire up views and URLS
