### ISSUE TITLE
USER STORY: Edit Quantity from items in Cart

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#25]
As a **Site User** I can **adjust the quantity of a product in my cart** so that **purchase the quantity I desire**

#4 Shopping Cart

### Acceptance Criteria
As a Site User, when I navigate to my Cart I can increase or decrease the quantity.

### Tasks
- [x] Create + and - buttons 
- [x] Add an update button
- [x] Wire up views and URLS

**Comment by kerstin-w** [comment]
Error Message on Shopping Bag page needs to be tested.
`if (quantity >= 1 && quantity <= 99) {
            form.submit();
        } else {
            messages.error(request, 'Please enter a quantity between 1 and 99');
            return false;
        }`
