### ISSUE TITLE
USER STORY: Remove items from Cart

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#25]
As a **Site User** I can **delete products from my cart** so that **I don't have to purchase the product in case I changed my mind**

#4 Shopping Cart and Checkout

### Acceptance Criteria
Given that I am a Site User, when I navigate to my Cart I can remove products.

### Tasks
- [ ] Create an "Delete from Cart" button.
- [ ] Wire up views and URLS
- [ ] Ensure order total is updated
