### ISSUE TITLE
USER STORY: Remove items from Cart

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#26]
As a **Site User** I can **delete products from my cart** so that **I don't have to purchase the product in case I changed my mind**

#4 Shopping Cart

### Acceptance Criteria
As a Site User, when I navigate to my Cart I can remove products.

### Tasks
- [x] Create an "Delete from Cart" button.
- [x] Wire up views and URLS
- [x] Ensure order total is updated
