### ISSUE TITLE
USER STORY: Checkout

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#27]
As a **Site User** I am **redirected to a checkout page** so that **I can make a purchase**

#4  Shopping Cart and Checkout

### Acceptance Criteria
Given that I am a Site User who is making a purchase, I should be redirected to a secure checkout page and clearly see a space to enter my card details.
Given that I am a Site User who is making a purchase, I can clearly see a space to enter my personal details for the purchase.
Given that I am a Registered User who is making a purchase, I have my personal details prefilled out in case I saved them.
Given that I am a Registered User who is making a purchase, I have the option to save my personal details for my next purchase.
Given that I am a Site User who is making a purchase, I can clearly see a space to enter my card details.

### Tasks
- [ ] Create Form for Checkout
- [ ] Create view for checkout
- [ ] _Get User information for registered users (if saved)_
- [ ] _Give the option to save user information if user is logged in_
- [ ] Implement Stripe payment functionality for inputting and processing card payments.
- [ ] Wire up view and URL
