### ISSUE TITLE
USER STORY: Checkout 

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#28]
As a **Site User** I am **redirected to a checkout page** so that **I can make a purchase**

#4  Shopping Cart and Checkout

### Acceptance Criteria

- As a Site User who is making a purchase, I should be redirected to a secure checkout page and clearly see a space to enter my card details.
- As a Site User who is making a purchase, I can clearly see a space to enter my personal details for the purchase.
- As a Registered User who is making a purchase, I have my personal details prefilled out in case I saved them.
- As a a Registered User who is making a purchase, I have the option to save my personal details for my next purchase.
- As a Site User who is making a purchase, I can clearly see a space to enter my card details.

### Tasks
- [x] Create Form for Checkout
- [x] Create view for checkout
- [x] _Get User information for registered users (if saved)_
- [x] _Give the option to save user information if user is logged in_
- [x] Implement Stripe payment functionality for inputting and processing card payments.
- [x] Wire up view and URL
