### ISSUE TITLE
USER STORY: Update account

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#29]
As a **Registered User** I can **edit my account** so that **personal data stays up to date**

### Acceptance Criteria
- When I am logged into my account and viewing my profile, I should see an "Edit" button.
- When I click on the "Edit" button, I should be taken to a page where I can edit my personal details.
- The "Edit" button should not be visible to logged out users.
- Only logged-in users should be able to access the page for editing personal information.

### Tasks
- [ ] Create a button to edit account.
- [ ] Create form and view
- [ ] Link edit button to view and URL.
- [ ] Hide button from logged out users.
- [ ] Restrict access to logged in users
