### ISSUE TITLE
USER STORY: Order Confirmation

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#29]
As a **Site User** I can **see a confirmation of my purchase** so that **I am assured the purchase was successful**

#4  Shopping Cart and Checkout

### Acceptance Criteria
- As a Site User who makes a purchase, I should be shown a confirmation page with a summary of my purchase
- As a Site User who makes a purchase, I should receive a confirmation email with a summary of my purchase

### Tasks
- [x] Create a confirmation page
- [x] Setup confirmation email
- [x] Trigger email with purchase
