### ISSUE TITLE
USER STORY: Delete account

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#30]
As a **Registered User** I can **delete my account** so that **I can remove my footprint from the website if I am no longer useing it**

#3  Sign in and out - User Profile

### Acceptance Criteria
- When I click on the option to delete my account, I should be prompted to confirm the request.
- When I confirm the request, my account should be permanently deleted from the website.
- After my account is deleted, I should receive confirmation that the deletion was successful.

### Tasks
- [ ] Create a Delete account Button.
- [ ] Provide a modal to confirm
- [ ] After an account is deleted provide feedback to the user.
