### ISSUE TITLE
USER STORY: Update account 

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#30]
As a **Registered User** I can **edit my account** so that **personal data stays up to date**

#3 User Profile

### Acceptance Criteria

- Given that I am logged into my account when I am viewing my profile then I should be able to edit my personal details.
- Given that I am logged into my account when I click on the edit button on my profile page then I should be taken to a page to edit the details.

### Tasks
- [x] Create a button to edit account.
- [x] Create form and view
- [x] Link edit button to view and URL.
- [x] Hide button from logged out users.
- [x] Restrict access to logged in users
