### ISSUE TITLE
USER STORY: Delete account

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#31]
As a **Registered User** I can **delete my account** so that **I can remove my footprint from the website if I am no longer useing it**

#3  Sign in and out - User Profile

### Acceptance Criteria

- As a registered user when I click on the option to delete my account then I am requested to confirm the request.
- As a registered user when I click on the option to delete my account And, When I confirm the request then my account is deleted.
- As a registered user when I delete my account then I should receive confirmation of the account deletion.

### Tasks
- [x] Create a Delete account Button.
- [x] Provide a modal to confirm
- [x] After an account is deleted provide feedback to the user.
