### ISSUE TITLE
USER STORY: View customer reviews

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#35]
As a **Site User** I can **view reviews of products on the online store** so that **I can make an informed decision before making a purchase**

#6 Customer Review

### Acceptance Criteria
- The shop should have a section dedicated to customer reviews for each product on the PDP
- The reviews should be displayed prominently on the PDP
- Customers should be able to sort reviews by rating
- The rating should be visiable on the CLP

### Tasks
- [x] Create a section for customer reviews on each PDP.
- [x] Options for customers to sort reviews by rating.
- [x] Indicate stars already on the top of the PDP
