### ISSUE TITLE
USER STORY: Write Reviews

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#35]
As a **customer** I can **leave a review for a product I have purchased** so that **I can share my experience with others**

#6 Customer Review

### Acceptance Criteria
- The online store should have a section where customers can leave a review for a product they have purchased.
- Customers should be able to rate the product and provide a written review.

### Tasks
- [ ] Create a section where customers can leave a review for each product they have purchased in the order history
- [ ] Create Form for the review
- [ ] Create a view
- [ ] Provide options for customers to rate the product and provide a written review.
