### ISSUE TITLE
USER STORY: Write Reviews

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#36]
As a **registered user** I can **leave a review for a product I have purchased** so that **I can share my experience with others**

#6 Customer review

### Acceptance Criteria
- The online store should have a section where customers can leave a review for a product they have purchased.
- Customers should be able to rate the product and provide a written review.

### Tasks
- [x] Create a section where customers can leave a review for each product they have purchased in the order history
- [x] Create Form for the review
- [x] Create a view
- [x] Provide options for customers to rate the product and provide a written review.
