### ISSUE TITLE
USER STORY: Create Wishlist

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#39]
As a **registered user** I can **create and add products to my wishlist** so that **I can keep track of products that I am interested in and plan future purchases more easily**

#8 Wishlist

### Acceptance Criteria

- Users should be able to add products to their wishlist by clicking on an "Add to Wishlist" button on the product page.
- The user's wishlist should be displayed in a clear and easy-to-read format, with the product name, image, and price displayed.
- Users should be able to remove products from their wishlist by clicking on a "Remove from Wishlist" button on the product page.

### Tasks

- [x] Implement functionality to add products to the wishlist.
- [x]  display the wishlist to the user.
- [x] Implement functionality to remove products from the wishlist.
