### ISSUE TITLE
USER STORY: Dashboard

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#41]
As a **Superuser** I can **have a dashbaord in the admin panel** so that **I can view and manage key metrics**

### Acceptance Criteria

- The dashboard should be accessible only to the superuser and provide an overview of key metrics and data
- The dashboard should display relevant KPIs, including but not limited to the total number of orders, revenue
- The dashboard should update in real-time or near-real-time, displaying the most up-to-date data available in the system.
- The dashboard should provide value to the superuser by helping them make data-driven decisions and better manage the store.

### Tasks

- [x] Implement the views
- [x]  Implement templates and URL
- [x] Implement authentication and authorization for the dashboard
