### ISSUE TITLE
USER STORY: Error Page

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#42]
As a **Site User** I can **be routed to a error page in case a page is not found** so that **I understand the error and click on a link to get back to the homepage**

### Acceptance Criteria
- The error page should clearly communicate to the user that the page they were trying to access cannot be found.
- The error page should provide suggestions for what the user can do next, such as navigating to the homepage
- The error page should be visually appealing and consistent with the rest of the website's design.

### Tasks
- [x] Create a custom error page that is distinct from the default browser error page.
- [x] Write clear and concise copy that suggests next steps for the user.
- [x] Create View to handle the error page
- [x] Link the error page to the appropriate error view
