### ISSUE TITLE
USER STORY: Sitemap and robtos.txt

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#43]
As a **site owner** I want **to create a sitemap and robots.txt file for my website** so that **search engines can properly index and crawl my pages**

### Acceptance Criteria

- The sitemap file should follow the XML sitemap protocol.
- The sitemap should include all pages on the website that I want indexed by search engines.
- The robots.txt file should include instructions for search engines to follow when crawling my website.
- The robots.txt file should exclude any pages that I do not want indexed by search engines.
- Both files should be stored in the root directory of my website.
- Both files should be accessible and readable by search engine crawlers.

### Tasks
- [x] Identify all pages on the website that should be included in the sitemap.
- [x] Use a sitemap generator tool to create an XML sitemap file.
- [x] Upload the sitemap file to the root directory of the website.
- [x] Test that the sitemap file is accessible and readable by search engine crawlers.
- [x] Identify any pages on the website that should be excluded from search engine indexing.
- [x] Create robots.txt file with the appropriate exclusions
- [x] Upload the robots.txt file to the root directory of the website.
- [x] Test that the robots.txt file is accessible and readable by search engine crawlers.
