### ISSUE TITLE
USER STORY: Home page

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#8]
As a **Site User** I want **to navigate tot he landing page firstly** so that **I can see what the store is about**

#1 

### Acceptance Criteria
- Given that I am a user of the website I am brought to the Home page first
- Display a Call-to-Action on the hero banner
- Display featured parts of the assortment
- Display products to purchase
- Display Footer with information 

### Tasks
- [ ] Ensure URL for the home page is the first point of contact
- [ ] Create a hero banner with CTA
- [ ] Create callouts for featured parts of the assortment
- [ ] Create a banner with "Reasons Why" to purchase
- [ ] Create a segment with products to purchase directly from the home page
- [ ] Create a footer
