### ISSUE TITLE
USER STORY: Home page

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Bike-World#9]
As a **Site User** I want **to navigate to the landing page firstly** so that **I can see what the store is about**

#1 Landing Page

### Acceptance Criteria
- Given that I am a user of the website I am brought to the Home page first
- Display a Call-to-Action on the hero banner
- Display featured parts of the assortment
- Display products to purchase
- Display Footer with information 

### Tasks
- [x] Ensure URL for the home page is the first point of contact
- [x] Create a hero banner with CTA
- [x] Create callouts for featured parts of the assortment
- [x] Create a banner with "Reasons Why" to purchase
- [x] Create a segment with products to purchase directly from the home page
- [x] Create a footer
